name: gymbuddy
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_signin_button: ^2.0.0
  shared_preferences: ^2.5.1
  http: ^1.3.0
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  webview_flutter: ^4.10.0
  webview_flutter_android: ^4.3.1
  webview_flutter_wkwebview: ^3.18.0
  flutter_stripe: ^11.4.0
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  sensors_plus: ^6.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
